### ISSUE TITLE
Course outline

### ISSUE THREAD

**Issue by andreasohlund** [Particular/SagaMasterClass#1]
Task force: @andreasohlund @DavidBoike
- Where does sagas fit in a soa/microservices arch
- Saga design
  - Controller vs Observer sagas
- concurrency considerations, how the storage provides serialization
- How concurrent access to instances can create congestion
  - See if we can create a append only saga using NH (scatter/gatter)
- How auto correlation works, use a "integration sample" example
- Never ending sagas, death to the batch job, http://docs.particular.net/nservicebus/sagas/#ending-a-long-running-process
- How to select storage?
- Do not query the database from your sagas
- Integration sagas
- Sagas as your domain model
- Saga not found
- Use of saga state vs timeout state
- Migrating saga state btw versions
- Recheduling timeouts
- The future of NSB sagas
- Visualization and debugging with ServiceInsight"
- Custom saga finder
  - Single instance sagas
### Machine setup
- Visual Studio 2013/2015
- MSMQ
- SqlServer + Management Studio
- ServiceInsight + ServiceControl

**Comment by mauroservienti** [comment]
> Sagas as your domain model

If this is `Sagas as Aggregates` then I love it :-)

**Comment by andreasohlund** [comment]
That was the plan yes :)

**Comment by seanfarmar** [comment]
Choreography ruther than orchestration?

**Comment by mauroservienti** [comment]
> Choreography

I like the metaphor

**Comment by andreasohlund** [comment]
How about we make the first exercise the abandoned cart saga?

http://joshkodroff.com/blog/2015/08/21/an-elegant-abandoned-cart-email-using-nservicebus/

Gets them going with the basics and that could kickoff the OrderPlaced event that we can build on for the next set of exercises?
